dist: trusty
language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)